// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function Changelog() {
  return window['go']['main']['App']['Changelog']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DaemonAddr() {
  return window['go']['main']['App']['DaemonAddr']();
}

export function InstallUpdateFromPeer(arg1) {
  return window['go']['main']['App']['InstallUpdateFromPeer'](arg1);
}

export function InstallUpdateFromURL(arg1) {
  return window['go']['main']['App']['InstallUpdateFromURL'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function SelectBackupFile(arg1) {
  return window['go']['main']['App']['SelectBackupFile'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectSaveFile(arg1, arg2) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function UpdateGreeting() {
  return window['go']['main']['App']['UpdateGreeting']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
