// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo():Promise<Record<string, string>>;

export function Changelog():Promise<string>;

export function CheckForUpdate():Promise<Record<string, any>>;

export function DaemonAddr():Promise<Record<string, string>>;

export function InstallUpdateFromPeer(arg1:string):Promise<string>;

export function InstallUpdateFromURL(arg1:string):Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function UpdateGreeting():Promise<Record<string, string>>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
